### ISSUE TITLE
bundling: UnableToResolveError: Unable to resolve module `../node_modules/react-native/packager/api/server/collections

### ISSUE THREAD

**Issue by mahadoang** [DAB0mB/ReactNativeMeteorBoilerplate#1] opened 2017-04-21 14:35 UTC
error: bundling: UnableToResolveError: Unable to resolve module `../node_modules/react-native/packager/api/server/collections` from `/Users/mahadoang/meteor/meteor-reactnative/src/App.js`: Directory /Users/mahadoang/meteor/meteor-reactnative/node_modules/react-native/packager/api/server/collections doesn't exist
    at UnableToResolveError (/Users/mahadoang/meteor/meteor-reactnative/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:488:5)
    at Promise.resolve.then (/Users/mahadoang/meteor/meteor-reactnative/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:445:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Bundling `index.ios.js`  94.5% (387/398), failed.

**Comment by DAB0mB** [comment] 2017-04-21 15:50
@mahadoang It seems like the plugin `module-alias` defined in the `.babelrc` file doesn't work for some reason. The loaded module should be `/Users/mahadoang/meteor/meteor-reactnative/api/server/collections` instead. Weird. I'm using Linux OS, guess yours is Mac OS. I haven't tested it on an iPhone, but as I said, the source for the problem is within the `module-alias` plugin. I will try to find a way to work it out, but if you've found a solution, do tell.

**Comment by DAB0mB** [comment] 2017-05-05 16:41
I'm closing this issue because I don't wanna spam the issues section, until this pops up again but for someone else.

**Closed by DAB0mB** 2017-05-05 16:41 UTC
